---
- name: Unarchive 
  ansible.builtin.unarchive:
    src: /tmp/artifact.tar.gz
    dest: .
    remote_src: yes

- name: start 
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  
